<a href="https://colab.research.google.com/github/Resuffid/PSR/blob/main/Homeworks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1

In [1]:
print("Hello world!")
a = 1
b = 2
a + b

Hello world!


3

# Week 2

In [2]:
hw1 = 21
hw2 = 14
hw3 = 18
hw4 = 23
hw5 = 19
hw6 = 21

In [3]:
mean = (hw1 + hw2 + hw3 + hw4 + hw5 + hw6)/6

In [4]:
print(mean)

19.333333333333332


In [5]:
print(round(mean, 2))

19.33


# Week 3

In [6]:
# The variable x - it can be changed by an user

x = 23

In [7]:
if x > 10:
  print('x is larger than 10')
elif x == 10:
  print('x is equal 10')
else:
  print('x is not larger than 10')


x is larger than 10


In [8]:
if x > 0:
  print('x is positive')
elif x == 0:
  print('x is equal zero')
else:
  print('x is negative')

x is positive


In [9]:
if x % 3 == 0:
  print('x is divisible by 3')
else:
  print('x is not divisible by 3')

x is not divisible by 3


In [10]:
(x % 3 == 0) and (x % 7 == 0)

False

In [11]:
(x < 100) and (not (x % 6 == 0))

True

In [13]:
if type(x) is float:
  print('x is float')
elif type(x) is int:
  print('x is an integer')
else:
  print('x is neither a float nor an integer')

x is an integer


# Week 4

In [36]:
with open('boys.txt') as f:
  names_f = f.read()
  names = names_f.splitlines()

In [37]:
names[:10]

['Liam',
 'Noah',
 'Oliver',
 'Elijah',
 'James',
 'William',
 'Benjamin',
 'Lucas',
 'Henry',
 'Theodore']

In [38]:
names.index('Ezekiel')

52

In [39]:
top20 = names[:20]

In [40]:
top20

['Liam',
 'Noah',
 'Oliver',
 'Elijah',
 'James',
 'William',
 'Benjamin',
 'Lucas',
 'Henry',
 'Theodore',
 'Jack',
 'Levi',
 'Alexander',
 'Jackson',
 'Mateo',
 'Daniel',
 'Michael',
 'Mason',
 'Sebastian',
 'Ethan']

In [41]:
sorted(top20)

['Alexander',
 'Benjamin',
 'Daniel',
 'Elijah',
 'Ethan',
 'Henry',
 'Jack',
 'Jackson',
 'James',
 'Levi',
 'Liam',
 'Lucas',
 'Mason',
 'Mateo',
 'Michael',
 'Noah',
 'Oliver',
 'Sebastian',
 'Theodore',
 'William']

In [57]:
names[:-10:-1]

['Xavier',
 'Dominic',
 'Carson',
 'Connor',
 'Austin',
 'Weston',
 'Beau',
 'Parker',
 'Nicholas']

In [58]:
name1 = 'Noah'
name2 = 'Liam'

In [61]:
names.index(name1)

1

In [62]:
if names.index(name1) > names.index(name2):
  print(f'{name1} is more popular than {name2}')
elif names.index(name1) < names.index(name2):
  print(f'{name1} is less popular than {name2}')

Noah is more popular than Liam


# Week 5

In [26]:
import numpy as np

l = list(np.random.randint(0, 100, 10000))

In [34]:
i = 0
j = 0
for n in l:
  i = i + n
  m = i/10000
print(m)


49.1544


In [32]:
j

1

In [35]:
i = 0
j = 0
for n in l:
  i = i + ((n - m) ** 2)
  sd = (i/10000)**0.5
print(sd)

28.72209533860634


# Week 6

In [36]:
pol = ['gorący', 'dzień', 'las', 'słońce']
eng = ['hot', 'day', 'forest', 'sun']

In [51]:
slo = dict(zip(eng, pol))

In [43]:
sent = 'The sun light the forest on a hot day'

In [47]:
s = str.split(str.lower(sent))

In [53]:
for n in s:
  if n in slo.keys():
    print(slo[n])
  else:
    print(n)

the
słońce
light
the
las
on
a
gorący
dzień


# Week 7

In [1]:
import numpy as np

l = list(np.random.randint(0, 100, 100))

In [23]:
def M(m):
  i = 0
  for n in m:
    i = i+n
    mean = i/len(m)
  return(mean)

In [24]:
M(l)

49.12

In [25]:
type(M(l))

numpy.float64

In [28]:
def std(m):
  i = 0
  for n in m:
    i = i + ((n - M(m))**2)
    sd = (i/len(m))**0.5
  return(sd)



In [29]:
std(l)

26.04698830959157

In [45]:
def zv(m):
  for n in m:
    print((n - M(m))/std(m))

In [46]:
zv(l)

-1.1179795396643541
-1.1179795396643541
1.3775105042292937
-0.4269207582784209
0.41770664119327533
-0.5420972218427431
-1.3867246213144393
-0.5037050673213024
-0.9260187670571505
0.4944909502361568
0.6096674138004791
-1.732254012007406
0.3025301776289531
0.763236031886242
-0.6188815308856246
-1.6554697029645244
-0.3117442947140987
1.18554973162209
-0.3117442947140987
1.2239418861435307
-0.849234458014269
-0.6572736854070653
0.11056940502174942
0.9935889590148864
0.916804649972005
0.763236031886242
1.4159026587507344
-0.19656783114977647
1.6078634313579383
1.646255585879379
-1.6170775484430837
-0.8108423034928283
0.14896155954319015
-1.1179795396643541
0.22574586858607162
-0.5037050673213024
-1.271548157750117
0.22574586858607162
1.5310791223150568
0.6096674138004791
0.8784124954505642
0.14896155954319015
-0.3885286037569802
-0.00460705854257279
0.3025301776289531
0.8400203409291235
1.5310791223150568
0.07217725050030868
-1.7706461665288467
0.8784124954505642
1.646255585879379
0.2257458

# Week 8

In [57]:
def translate_word(word, dictionary, return_original=False, ignore_case=True):
  if return_original==False:
    if word in dictionary:
      return(dictionary[word])
    else:
      return(None)
  if word in dictionary:
    return(dictionary[word])
  else:
    return(word)
  if ignore_case==True:
    str.lower(word)
    """Finds word in a dictionary and returns translation.

    This function takes a word in one language and a dictionary containing 
    translations as arguments. It looks for a word in the dictionary and, if found
    returns the translation. If the word is not in the dictionary, the function returns
    None or, the original word if return_original=True. The ignore_case argument specifies
    if the search should be case-sensitive or not.

    Parameters
    ----------
    word : str
        A word to look up in the dictionary.
    dictionary: dict
        A dictionary containing words (keys) and their translations (values).
    return_original: bool
        If true, the function returns the original word if no translation is found.
    ignore_case: bool
        If true, the words and translations are both converted to lowercase and than compared.

    Returns
    -------
    str, None
        A translated word, an original word or None.

    """


In [51]:
pol = ['gorący', 'dzień', 'las', 'słońce']
eng = ['hot', 'day', 'forest', 'sun']

In [52]:
slo = dict(zip(eng, pol))

In [61]:
translate_word('hot', slo)

'gorący'

In [62]:
translate_word('stop', slo, True)

'stop'

In [59]:
translate_word('stop', slo, False)

# Week 9

In [70]:
rng = np.random.default_rng()

In [72]:
a = rng.normal(1,10,(10,10))

In [73]:
print(a)

[[ -9.25419908   3.72119965  -4.71873906   7.71238263  -7.39561978
   -7.3619629    7.35844995  10.48347303  22.89756421  30.1594806 ]
 [  4.23415377   3.04042379 -13.33377863  22.04844109  -9.4188165
   12.29102391  11.65315543  25.08662314 -14.65674365   4.22013563]
 [  1.17430003   3.21943702   2.77291464   0.0466666  -21.74939408
    1.95323072 -11.95371991   2.92014512  -3.16493778 -11.26704772]
 [  7.96801095  -9.50849421  -1.98605121  -8.45907536  11.40136694
  -13.06647672 -15.9391985   -1.15606214   6.68265774  -5.65049434]
 [ -2.51620058  17.73581473   7.75072774  -0.3108207    3.0869132
  -21.95077824   0.25304134  -4.41266429  29.19482129   7.69601357]
 [  3.92716      6.03032644  -5.89542108  12.18161875  13.23365676
   -6.85298755 -14.34006936 -16.00407725  -8.24282294 -16.30634928]
 [  6.28003822  13.80361033   6.27234009 -12.3722267    7.00511695
  -13.12789347 -12.86490628  -1.80834192   8.5464523   25.37540684]
 [ -1.72971935  -8.95591369  -2.54031799  -7.02088768  -2

In [75]:
a[1, 0:5]

array([  4.23415377,   3.04042379, -13.33377863,  22.04844109,
        -9.4188165 ])

In [77]:
a[-2:, -1]

array([ 2.44849246, -2.1786456 ])

In [80]:
a.mean(axis=1)

array([ 5.36020292,  4.5164618 , -3.60484054, -2.97138168,  3.65268681,
       -3.22689655,  2.71095964, -2.03483455, -6.68827906,  2.67128654])

In [81]:
a.std(axis=1)

array([12.65208883, 13.13262774,  8.09147299,  8.7966723 , 12.92326244,
       10.71685112, 12.06665672,  4.96231905,  9.0052816 ,  8.50384994])